version: "3"
services:
  react_app:
    build: ./client
    image: austinabro321/react_greeting
    ports:
      - 6001:5000
    networks:
      - greeting_app
  node_api:
    build: ./server
    image: austinabro321/node_greeting
    ports:
      - 4000:3000
    depends_on: 
      - postgres
    networks:
      - greeting_app
  postgres:
    image: postgres:13.1-alpine
    ports: 
      - 5432:5432
    volumes: 
      - /dbdata:/var/lib/postgresql/data
    networks:
      - greeting_app
    restart: always
    environment:
      POSTGRES_USER: $psuser
      POSTGRES_PASSWORD: $password
volumes:
  dbdata:    
networks:
  greeting_app:
    driver: bridge