apiVersion: v1
kind: Pod
metadata:
  name: greeting-app
  labels:
    app: greeting_app_label
spec:
  containers:
  - name: node-greeting
    image: austinabro321/node_greeting:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3000

