apiVersion: v1
kind: Service
metadata:
  name: greeting-svc
spec:
  type: NodePort
  selector:   
    app: greeting_app_label
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 31111
    protocol: TCP
