apiVersion: v1
kind: Service
metadata:
  name: greeting-svc-lb
spec:
  type: LoadBalancer
  selector:   
    app: greeting_app_label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
