apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting
spec:
  replicas: 2
  selector:
    matchLabels:
      app: greeting_app_label
  template:
    metadata:
      labels:
        app: greeting_app_label
    spec:
      containers:
      - name: myapp
        image: example-image
        imagePullPolicy: Always
        resources:
          limits:
            memory: "32Mi"
            cpu: "128m"
        ports:
        - containerPort: 3000
