name: test

on: [ push,workflow_dispatch ]

jobs:
  docker:
    name: "docker"
    runs-on: [self-hosted, linux]
    steps:
    # - uses: actions/checkout@v2
    - name: check size
      run: |
        echo "total"
        df -h
        echo "in tool cache"
        du -sh $RUNNER_TOOL_CACHE
    # - name: docker build nodejs
    #   id: build-node
    #   run: |
    #     docker build ./server/ -t austinabro321/node_greeting:latest
