name: test

on: [ push,workflow_disptach ]

jobs:
  docker:
    name: "docker"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: docker build nodejs
      id: build-node
      run: |
        docker build ./server -t austinabro321/node_greeting:latest
