name: test

on: [ push,workflow_dispatch ]

jobs:
  docker:
    name: "docker"
    runs-on: ubuntu-latest
    steps:
    - name: docker build nodejs
      id: build-node
      run: |
        docker build ./server/dockerfile -t austinabro321/node_greeting:latest
